name: LXD-CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone this repository
      uses: actions/checkout@v2

    - name: Build LXD package
      run: |
        make build
        make print-env | tee $GITHUB_ENV

    - name: Upload LXD package
      uses: actions/upload-artifact@v2.2.3
      with:
        name: ${{ env.LXD_PACKAGE_DEB }}
        path: ${{ env.LXD_PACKAGE_DEB }}
